### ISSUE TITLE
(Закрыт) 

### ISSUE THREAD

**Issue by Void-119** [kazetechdev/skillcraft-studio#1]
1. ну request в асинхронности это костыль
2. openai можно и без библиотеки юзать 
3. slash файл можно разбить по файлам для читабельности

**Comment by kazetechdev** [comment]
Незнаем зачем Вам это надо было писать в репе, который носит лишь демонстрационный характер и ваш комментарий вообще ни на что не повлияет. 🥱

**Comment by kazetechdev** [comment]
> 1. ну request в асинхронности это костыль
> 2. openai можно и без библиотеки юзать 
> 3. slash файл можно разбить по файлам для читабельности 

Незнаем зачем Вам это надо было писать в репе, который носит лишь демонстрационный характер и ваш комментарий вообще ни на что не повлияет. 🥱
